export const metadata = { title: "Terms of Service - Creator Dashboard" };

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto flex max-w-2xl flex-col gap-6 py-4 text-sm leading-relaxed">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: [DATE]</p>
      </div>

      <Section title="1. Agreement">
        <p>
          These Terms govern your use of Creator Dashboard (&quot;the Service&quot;), operated by
          [YOUR BUSINESS / LEGAL NAME] (&quot;we&quot;, &quot;us&quot;). By creating an account or
          connecting your Instagram account, you agree to these Terms and to our{" "}
          <a href="/privacy" className="underline">
            Privacy Policy
          </a>
          .
        </p>
      </Section>

      <Section title="2. The Service">
        <p>
          The Service connects to your own Instagram Business or Creator account via
          Instagram&apos;s official Graph API to display analytics, and - where enabled -
          generate AI-assisted content suggestions and summaries. You must own or be authorized
          to manage the Instagram account you connect.
        </p>
      </Section>

      <Section title="3. Accounts & subscriptions">
        <p>
          Some features may require a paid subscription. Subscription pricing, billing frequency,
          and cancellation terms are presented at the time of purchase. Unless stated otherwise,
          subscriptions renew automatically until cancelled, and you can cancel at any time from
          your account settings; cancellation takes effect at the end of the current billing
          period. [ADD REFUND POLICY HERE ONCE DEFINED.]
        </p>
      </Section>

      <Section title="4. Acceptable use">
        <p>You agree not to:</p>
        <ul className="ml-5 list-disc space-y-1">
          <li>Use the Service to access an Instagram account you don&apos;t own or control.</li>
          <li>Attempt to circumvent the Service&apos;s access controls or rate limits.</li>
          <li>
            Use the Service in a way that violates Instagram&apos;s or Meta&apos;s own terms and
            policies.
          </li>
          <li>Resell or redistribute data obtained through the Service without authorization.</li>
        </ul>
      </Section>

      <Section title="5. AI-generated content">
        <p>
          Suggestions, summaries, and scripts generated by the Service are produced by an AI
          model and are provided as a starting point only. You are responsible for reviewing and
          editing any AI-generated content before publishing it, and for ensuring it complies
          with Instagram&apos;s content policies and applicable law.
        </p>
      </Section>

      <Section title="6. Disclaimer of warranties">
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind, express or
          implied. We do not guarantee the accuracy of analytics data (which depends on data
          provided by Instagram&apos;s API) or that the Service will be uninterrupted or
          error-free.
        </p>
      </Section>

      <Section title="7. Limitation of liability">
        <p>
          To the fullest extent permitted by law, [YOUR BUSINESS / LEGAL NAME] will not be liable
          for any indirect, incidental, or consequential damages arising from your use of the
          Service.
        </p>
      </Section>

      <Section title="8. Termination">
        <p>
          You may stop using the Service and disconnect your Instagram account at any time. We
          may suspend or terminate access if these Terms are violated, or if required to comply
          with Instagram/Meta&apos;s platform policies.
        </p>
      </Section>

      <Section title="9. Governing law">
        <p>These Terms are governed by the laws of [JURISDICTION].</p>
      </Section>

      <Section title="10. Changes">
        <p>
          We may update these Terms from time to time. Continued use of the Service after a
          change constitutes acceptance of the updated Terms.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these Terms? Email{" "}
          <a href="mailto:[SUPPORT EMAIL]" className="underline">
            [SUPPORT EMAIL]
          </a>
          .
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="text-base font-semibold">{title}</h2>
      {children}
    </section>
  );
}
